# Dockerfile.react
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY ai-helper/package*.json ./
RUN npm install

# Copy the rest of the application code
COPY ai-helper/ ./

# Build the React app for production
RUN npm run build

# Install 'serve' globally to serve the app
# RUN npm install -g serve

# Expose port 3000 for the React app
EXPOSE 3000

# Serve the build folder
CMD ["npm", "run", "start"]
